baseURL: "https://blog.jeffery.tk/"
languageCode: "zh-tw"
title: "Jeffery's Blog"
pygmentsstyle: 'monokai'
metaDataFormat: yaml

# Theme settings
theme: novela
# module:
#   imports:
#     - path: "github.com/forestryio/hugo-theme-novela"
paginate: 6
social:
  twitter: "#"
  github: "https://github.com/chiachun2491/"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
taxonomies:
  author: authors
  category: categories
